name: Java CI with Gradle

on:
  push:
    branches: [ "main", "sharapovdv" ]
  pull_request:
    branches: [ "main", "sharapovdv" ]
  schedule:
    - cron: '30 12 * * 3'  # Среда 12:30 UTC
    - cron: '0 22 * * 5'   # Пятница 22:00 UTC

jobs:
  build:
    strategy:
      matrix:
        java: ['11', '17', '21']  # LTS-версии (Temurin не поддерживает 13)
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - java: '13'            # Для не-LTS версий
            distribution: 'zulu'  # Альтернативный дистрибутив
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4  # Обновлено до v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution || 'temurin' }}  # По умолчанию Temurin

      - name: Build and Test with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build test
